# Generated by Django 4.2.20 on 2025-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_orders', '0003_remove_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Готово', 'Готово'), ('Оплачено', 'Оплачено')], max_length=20, verbose_name='статус заказа'),
        ),
    ]
