# Generated by Django 4.2.20 on 2025-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'В ожидании'), ('Ready', 'Готово'), ('Paid', 'Оплачено')], max_length=20, verbose_name='статус заказа'),
        ),
    ]
