version: '3.8'
volumes:
  static_value:

services:

  web:
    build: .
    restart: always
    volumes:
      - static_value:/code/orders/static/
      - ./orders/db/:/code/orders/db/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web